### ISSUE TITLE
Semantic Kernel integration

### ISSUE THREAD

**Issue by rudi77** [rudi77/taskforce#12]

**Comment by rudi77** [comment]
Integrate SemanticKernel. Use it as the core framework for Agent development

**Comment by philippgrafendorfe** [comment]
Hello. Um was gehts hier nochmal genau? ist das ein Blumatix Projekt oder deins?

**Comment by rudi77** [comment]
Hello, wieso hast du das bekommen? Das ist meine Spielwiese für Agents.


Philionnaire ***@***.***> schrieb am Mo., 14. Okt. 2024,
15:47:
